name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 3000:3000
          - 8080:8080

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Run Docker Compose
      run: |
        docker-compose up --build -d

    - name: Check running containers
      run: |
        docker ps

    - name: Cleanup
      if: always()
      run: docker-compose down
