name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Auto Versioning"]
    types:
      - completed
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Get latest tag
      id: get_version
      run: echo "VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
  
    
    - name: Create .npmrc file
      run: |
        echo "@remla24-team12:registry=https://npm.pkg.github.com/" > ./backend/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.REMLA_TOKEN }}" >> ./backend/.npmrc

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REMLA_TOKEN }}

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend/
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/frontend:latest
          ghcr.io/${{ github.repository_owner }}/frontend:${{ env.VERSION }}
    
    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend/
        file: ./backend/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/backend:latest
          ghcr.io/${{ github.repository_owner }}/backend:${{ env.VERSION }}

    - name: Verify pushed image
      run: echo "Image pushed!"
